### ISSUE TITLE
CDNify jQuery?

### ISSUE THREAD

**Issue by rclai** [HedCET/cdnify#1]
Is this possible?

I was trying to ```meteor remove jquery``` and add the CDN jQuery, but it didn't work.

**Comment by sujith3g** [comment]
CDNify is meant for third party libraries like `moment.js`,`bootstrap`, etc.,  `jquery` is a standard-app-package so you cannot cdnify jquery. How did you removed the `jquery ` ?, `meteor remove jquery` gives me `jquery is not in this project`.

**Comment by rclai** [comment]
I could not remove jQuery.
